Update sonarcloud.yml

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -35,3 +35,10 @@ jobs:
             #-Dsonar.verbose= # optional, default is false
           # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
           projectBaseDir: .
+     
+      - name: Check SonarCloud Quality Gate
+        run: |
+          if [ "$(curl -s -u $SONAR_TOKEN: 'https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}' | jq -r '.projectStatus.status')" != "OK" ]; then
+            echo "Quality gate failed"
+            exit 1
+          fi
